@ExpenseApproval.Api_HostAddress = http://localhost:5119

### 1. Tạo Đề nghị chi phí mới
POST http://localhost:5119/api/expenses
Content-Type: application/json

{
  "requesterId": "22222222-2222-2222-2222-222222222222",
  "departmentId": "11111111-1111-1111-1111-111111111111",
  "amount": 5000000,
  "category": "Travel",
  "reason": "Chi phí công tác"
}

### 2. Gửi duyệt Đề nghị chi phí (Submit)
POST http://localhost:5119/api/expenses/56e5435a-1cc3-4908-9e27-3c3e7606b4ac/submit
Content-Type: application/json

{
  "userId": "22222222-2222-2222-2222-222222222222"
}

### 3. Duyệt đơn (Approve)
POST http://localhost:5119/api/expenses/31861e07-49f1-4ef5-a98c-73220c55f333/approve
Content-Type: application/json

{
  "userId": "33333333-3333-3333-3333-333333333333",
  "comment": "Đồng ý duyệt chi phí công tác"
}

### 4. Từ chối đơn (Reject)
POST http://localhost:5119/api/expenses/56e5435a-1cc3-4908-9e27-3c3e7606b4ac/reject
Content-Type: application/json

{
  "userId": "33333333-3333-3333-3333-333333333333",
  "comment": "Thiếu hóa đơn đính kèm, từ chối"
}

### 5. Thanh toán đơn (Mark Paid) - Dùng ID của Accountant
POST http://localhost:5119/api/expenses/31861e07-49f1-4ef5-a98c-73220c55f333/pay
Content-Type: application/json

{
  "userId": "55555555-5555-5555-5555-555555555555"
}
